# Global Variables for R CMD check
#
# This file silences "no visible binding" notes generated by
# dplyr and ggplot2 non-standard evaluation.
#
utils::globalVariables(c(
  "variant_id", "score", "modality", "gene", "gene_name", "coords",
  "quantile_score", "output_type", "scored_interval",
  "group", "val", "is_hit", "n_hits", "n_obs",
  "a", "b", "c", "d", "ft", "p_raw", "p_adj",
  "log2OR", "neg_log10_fdr", "class", "or", 
  "p_val", "median_diff",
  "gene_score", "n_variants",
  "chrom", "start", "end", "x", "y",
  ".data", "where", "range_part" 
))